--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.2.184.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 07/06/2020 03:01:48
-- Server version: 
--


INSERT INTO "Fyyur".public.artists(name, city, state, phone, genres, image_link, facebook_link, website, seeking_venue, seeking_description, insert_date, update_date, available_from, available_to) VALUES
(E'Guns N Petals', E'San Francisco', E'CA', E'326-123-5000', E'Rock n Roll', E'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80', E'https://www.facebook.com/GunsNPetals', E'https://www.gunsnpetalsband.com', true, E'Looking for shows to perform at in the San Francisco Bay Area!', '07/06/2020 02:27:40.299229 AD', null, '18:00:00.000000', '20:00:00.000000');
INSERT INTO "Fyyur".public.artists(name, city, state, phone, genres, image_link, facebook_link, website, seeking_venue, seeking_description, insert_date, update_date, available_from, available_to) VALUES
(E'Matt Quevedo', E'New York', E'NY', E'300-400-5000', E'Jazz', E'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80', E'https://www.facebook.com/mattquevedo923251523', E'https://www.Quevedo.com', false, E'', '07/06/2020 02:29:13.776948 AD', null, '16:00:00.000000', '18:00:00.000000');
INSERT INTO "Fyyur".public.artists(name, city, state, phone, genres, image_link, facebook_link, website, seeking_venue, seeking_description, insert_date, update_date, available_from, available_to) VALUES
(E'The Wild Sax Band', E'San Francisco', E'CA', E'432-325-5432', E'Classical,Jazz', E'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80', E'https://www.facebook.com/TheWildSaxBand', E'https://www.TheWildSaxBand.com', false, E'', '07/06/2020 02:29:55.823441 AD', null, '00:00:00.000000', '23:59:00.000000');