--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.2.184.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 07/06/2020 03:02:04
-- Server version: 
--


INSERT INTO "Fyyur".public.shows(venue_id, artist_id, start_time) VALUES
(2, 1, '07/08/2020 18:00:00.000000 AD');
INSERT INTO "Fyyur".public.shows(venue_id, artist_id, start_time) VALUES
(1, 3, '07/06/2020 20:00:00.000000 AD');
INSERT INTO "Fyyur".public.shows(venue_id, artist_id, start_time) VALUES
(2, 2, '07/06/2020 16:11:40.000000 AD');
INSERT INTO "Fyyur".public.shows(venue_id, artist_id, start_time) VALUES
(2, 3, '07/08/2020 02:42:52.000000 AD');
INSERT INTO "Fyyur".public.shows(venue_id, artist_id, start_time) VALUES
(3, 1, '07/08/2020 18:42:52.000000 AD');