--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.2.184.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 07/06/2020 03:02:19
-- Server version: 
--


INSERT INTO "Fyyur".public.venues(name, city, state, address, phone, genres, image_link, facebook_link, website, seeking_talent, seeking_description, insert_date, update_date) VALUES
(E'The Musical Hop', E'San Francisco', E'CA', E'1015 Folsom Street', E'123-123-1234', E'Classical,Folk,Jazz,Reggae', E'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60', E'https://www.facebook.com/TheMusicalHop', E'https://www.themusicalhop.com', true, E'We are on the lookout for a local artist to play every two weeks. Please call us.', '07/06/2020 02:31:39.399993 AD', null);
INSERT INTO "Fyyur".public.venues(name, city, state, address, phone, genres, image_link, facebook_link, website, seeking_talent, seeking_description, insert_date, update_date) VALUES
(E'The Dueling Pianos Bar', E'New York', E'NY', E'335 Delancey Street', E'914-003-1132', E'Classical,Hip-Hop,R&B', E'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', E'https://www.facebook.com/theduelingpianos', E'https://www.theduelingpianos.com', false, E'', '07/06/2020 02:32:39.304897 AD', null);
INSERT INTO "Fyyur".public.venues(name, city, state, address, phone, genres, image_link, facebook_link, website, seeking_talent, seeking_description, insert_date, update_date) VALUES
(E'Park Square Live Music & Coffe', E'San Francisco', E'CA', E'34 Whiskey Moore Av', E'415-000-1234', E'Classical,Folk,Jazz,Rock n Roll', E'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80', E'https://www.facebook.com/ParkSquareLiveMusicAndCoffe', E'https://www.parksquarelivemusicandcoffee.com', false, E'', '07/06/2020 02:33:40.480015 AD', null);